# Generated by Django 3.2.9 on 2021-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplecustomers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatar/%Y/%m/%d', verbose_name='Фото профиля'),
        ),
    ]
