# Generated by Django 4.0 on 2021-12-08 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contracts/%Y/%m/%d/', verbose_name='Файл договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('real_name', models.CharField(max_length=255, verbose_name='Физическое ФИО')),
                ('ur_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('real_address', models.CharField(max_length=255, verbose_name='Физический адрес')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contracts', verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=1.0, message='Неверная цена')], verbose_name='цена')),
                ('package', models.BooleanField(default=False, verbose_name='Упковка продукции')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=14, verbose_name='Штрих-код')),
            ],
        ),
        migrations.AddField(
            model_name='simplecustomers',
            name='about',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='simplecustomers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Фото профиля'),
        ),
        migrations.CreateModel(
            name='ProductForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vzxk.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vzxk.qrcode', verbose_name='Штрих-код продукта'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продуктов')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Общая цена заказа')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='Дата поступления')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления в пункт выдачи')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Заказчик')),
                ('products', models.ManyToManyField(to='vzxk.ProductForOrder')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('date_order', 'date_complete'),
            },
        ),
        migrations.AddField(
            model_name='contragent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.simplecustomers'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Контрагент'),
        ),
    ]
