# Generated by Django 3.2.9 on 2021-12-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0002_contracts_contragent_product_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfororder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.product'),
        ),
    ]
