# Generated by Django 3.2.9 on 2021-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0002_simplecustomers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecustomers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
    ]
