# Generated by Django 3.2.9 on 2021-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0003_alter_productfororder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общая цена заказа'),
        ),
    ]
