# Generated by Django 4.0 on 2021-12-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contragent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Заказчик'),
        ),
    ]
