# Generated by Django 3.2.9 on 2021-11-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0004_simplecustomers_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecustomers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Фото профиля'),
        ),
    ]
