# Generated by Django 3.2.9 on 2021-11-27 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0005_alter_simplecustomers_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Штрих-код')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('special_code', models.PositiveIntegerField(db_index=True, verbose_name='Код номенклатуры')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1.0, message='Неверная цена')], verbose_name='цена')),
                ('package', models.BooleanField(default=False, verbose_name='Упковка продукции')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vzxk.qrcode', verbose_name='Штрих-код продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
    ]
