# Generated by Django 3.2.9 on 2021-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0006_product_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_code',
            field=models.CharField(db_index=True, max_length=14, verbose_name='Код номенклатуры'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=14, verbose_name='Штрих-код'),
        ),
    ]
