# Generated by Django 3.2.9 on 2021-11-28 19:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vzxk', '0007_auto_20211127_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=22, verbose_name='Номер договора')),
                ('document', models.FileField(upload_to='contracts/%Y/%m/%d/', verbose_name='Файл договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('real_name', models.CharField(max_length=255, verbose_name='Физическое ФИО')),
                ('ur_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('real_address', models.CharField(max_length=255, verbose_name='Физический адрес')),
                ('code', models.CharField(max_length=5, verbose_name='Код номенклатуры')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contracts', verbose_name='Номер договора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=1.0, message='Неверная цена')], verbose_name='цена'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Номер заказа')),
                ('object_id', models.PositiveIntegerField()),
                ('address_to', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('number', models.PositiveIntegerField(verbose_name='Количество продуктов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Общая цена заказа')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='Дата поступления')),
                ('date_complete', models.DateTimeField(verbose_name='Дата поступления в пункт выдачи')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('date_order', 'date_complete'),
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Контрагент'),
        ),
    ]
