# Generated by Django 3.2.9 on 2021-11-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0008_auto_20211128_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vzxk.contragent', verbose_name='Контрагент'),
        ),
    ]
