# Generated by Django 3.2.9 on 2021-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0009_alter_contracts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Общая цена заказа'),
        ),
    ]
