# Generated by Django 3.2.9 on 2021-11-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0010_auto_20211128_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='object_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='vzxk.Product', verbose_name='Продукт'),
        ),
    ]
