# Generated by Django 3.2.9 on 2021-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0011_auto_20211130_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления в пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продуктов'),
        ),
    ]
