# Generated by Django 3.2.9 on 2021-11-30 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0012_auto_20211130_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vzxk.product')),
                ('number', models.PositiveIntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество не может быть меньше одного ')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Продукт заказа',
                'verbose_name_plural': 'Продукты заказа',
            },
            bases=('vzxk.product',),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='vzxk.ProductOrder', verbose_name='Продукт'),
        ),
    ]
