# Generated by Django 3.2.9 on 2021-11-30 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0013_auto_20211201_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество не может быть меньше одного ')], verbose_name='Количество'),
        ),
    ]
