# Generated by Django 3.2.9 on 2021-11-30 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0014_alter_productorder_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество не может быть меньше одного ')], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vzxk.product')),
            ],
            options={
                'verbose_name': 'Продукт заказа',
                'verbose_name_plural': 'Продукты заказа',
            },
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='vzxk.ProductsOrder', verbose_name='Продукт'),
        ),
    ]
