# Generated by Django 3.2.9 on 2021-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0016_auto_20211206_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='vzxk.Product'),
        ),
    ]
