# Generated by Django 3.2.9 on 2021-12-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0018_auto_20211206_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Колличество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vzxk.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт для заказа',
                'verbose_name_plural': 'Продукция для заказка',
                'ordering': ('product',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='vzxk.ProductForOrder'),
        ),
    ]
