# Generated by Django 3.2.9 on 2021-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0019_auto_20211207_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfororder',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
