# Generated by Django 3.2.9 on 2021-12-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0021_auto_20211207_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfororder',
            old_name='number',
            new_name='numbers',
        ),
    ]
