# Generated by Django 3.2.9 on 2021-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0022_rename_number_productfororder_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfororder',
            name='numbers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колличество'),
        ),
    ]
