# Generated by Django 3.2.9 on 2021-12-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0023_alter_productfororder_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfororder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vzxk.product', verbose_name='Продукт'),
        ),
    ]
