# Generated by Django 4.0 on 2021-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0024_alter_productfororder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='vzxk.ProductForOrder'),
        ),
    ]
