# Generated by Django 4.0 on 2021-12-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0025_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='code',
            new_name='qr_code',
        ),
    ]
