# Generated by Django 4.0 on 2021-12-08 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0026_rename_code_qrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfororder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1.0, message='Неверная цена')], verbose_name='цена'),
        ),
    ]
