# Generated by Django 4.0 on 2021-12-08 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0027_productfororder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfororder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1.0, message='Неверная цена')], verbose_name='цена'),
        ),
    ]
