# Generated by Django 4.0 on 2021-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0028_alter_productfororder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='vzxk.Product'),
        ),
        migrations.DeleteModel(
            name='ProductForOrder',
        ),
    ]
