# Generated by Django 4.0 on 2021-12-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzxk', '0029_alter_order_products_delete_productfororder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='code',
        ),
        migrations.RemoveField(
            model_name='contragent',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_code',
        ),
    ]
